Repository microsoft/mssql-python, pull requests merged in 2025-08, with the labels that each got.

#157 FIX: Making type objects and constructor compatible with pyodbc
  mssql_python/type.py
  tests/test_002_types.py
Labels: pr-size: medium

#158 FIX: Setting autocommit as False by default & add rollback on connection close
  mssql_python/connection.py
  mssql_python/db_connection.py
  mssql_python/pybind/connection/connection.cpp
  tests/test_003_connection.py
Labels: pr-size: small

#165 FEAT: Adding Cursor.connection attribute
  mssql_python/cursor.py
  tests/test_004_cursor.py
Labels: pr-size: medium

#185 FEAT: adding cursor.tables
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_004_cursor.py
Labels: pr-size: large

#184 FEAT: Adding Cursor.messages
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_004_cursor.py
Labels: pr-size: large

#181 FEAT: Adding cursor.skip(n)
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_004_cursor.py
Labels: pr-size: large

#180 FEAT: Adding cursor.scoll function
  mssql_python/constants.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_004_cursor.py
Labels: pr-size: large

#163 FEAT: Adding cursor.rownumber - DBAPI 2.0
  mssql_python/constants.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_004_cursor.py
Labels: pr-size: large

#162 FEAT: Adding __iter__ and .next functionality for cursor
  mssql_python/constants.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_004_cursor.py
Labels: pr-size: large

#164 FEAT: Adding Conn.Error
  mssql_python/connection.py
  mssql_python/cursor.py
  tests/test_003_connection.py
Labels: pr-size: medium

#160 FEAT: Context manager support for connection and cursor class
  mssql_python/connection.py
  mssql_python/cursor.py
  tests/test_003_connection.py
  tests/test_004_cursor.py
Labels: pr-size: medium

#172 FEAT: Adding conn.setencoding() API
  mssql_python/__init__.py
  mssql_python/connection.py
  mssql_python/helpers.py
  mssql_python/type.py
  tests/test_003_connection.py
Labels: pr-size: large

#166 FEAT: Support Emojis for data types
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  tests/test_004_cursor.py
Labels: pr-size: medium

#176 FEAT: Support for streaming large parameters in execute()
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
Labels: pr-size: medium

#210 FEAT: Linux SUSE Support
  README.md
  mssql_python/libs/linux/suse/x86_64/lib/libmsodbcsql-18.5.so.1.1
  mssql_python/libs/linux/suse/x86_64/lib/libodbcinst.so.2
  mssql_python/libs/linux/suse/x86_64/share/resources/en_US/msodbcsqlr18.rll
  mssql_python/pybind/README.md
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_000_dependencies.py
Labels: pr-size: small
