Repository microsoft/mssql-python, pull requests merged in 2025-07, with the labels that each got.

#116 CHORE: MacOS Library Cleanup
  .github/workflows/pr-format-check.yml
  mssql_python/libs/macos/lib/libltdl.7.dylib
  mssql_python/libs/macos/lib/libmsodbcsql.18.dylib
  mssql_python/libs/macos/lib/libodbc.2.dylib
  mssql_python/libs/macos/lib/libodbccr.2.dylib
  mssql_python/libs/macos/lib/libodbcinst.2.dylib
  mssql_python/libs/macos/share/doc/msodbcsql18/LICENSE.txt
  mssql_python/libs/macos/share/doc/msodbcsql18/RELEASE_NOTES
  mssql_python/libs/macos/share/msodbcsql18/resources/en_US/msodbcsqlr18.rll
  mssql_python/pybind/ddbc_bindings_mac.cpp
Labels: pr-size: large

#114 FEAT: Linux Driver Libraries
  mssql_python/libs/linux/debian_ubuntu/x86_64/lib/MICROSOFT_ODBC_DRIVER_FOR_SQL_SERVER_LICENSE.txt
  mssql_python/libs/linux/debian_ubuntu/x86_64/lib/libmsodbcsql-18.5.so.1.1
  mssql_python/libs/linux/debian_ubuntu/x86_64/lib/libodbcinst.so.2
  mssql_python/libs/linux/debian_ubuntu/x86_64/share/resources/en_US/msodbcsqlr18.rll
  mssql_python/libs/linux/rhel/x86_64/lib/MICROSOFT_ODBC_DRIVER_FOR_SQL_SERVER_LICENSE.txt
  mssql_python/libs/linux/rhel/x86_64/lib/libmsodbcsql-18.5.so.1.1
  mssql_python/libs/linux/rhel/x86_64/lib/libodbcinst.so.2
  mssql_python/libs/linux/rhel/x86_64/share/resources/en_US/msodbcsqlr18.rll
  mssql_python/libs/macos/arm64/lib/MICROSOFT_ODBC_DRIVER_FOR_SQL_SERVER_LICENSE.txt
  mssql_python/libs/macos/x86_64/lib/MICROSOFT_ODBC_DRIVER_FOR_SQL_SERVER_LICENSE.txt
  mssql_python/libs/windows/arm64/MICROSOFT_ODBC_DRIVER_FOR_SQL_SERVER_LICENSE.txt
  mssql_python/libs/windows/arm64/vcredist/MICROSOFT_VISUAL_STUDIO_LICENSE.txt
  mssql_python/libs/windows/x64/vcredist/MICROSOFT_VISUAL_STUDIO_LICENSE.txt
  mssql_python/libs/windows/x86/MICROSOFT_ODBC_DRIVER_FOR_SQL_SERVER_LICENSE.txt
  mssql_python/libs/windows/x86/vcredist/MICROSOFT_VISUAL_STUDIO_LICENSE.txt
  mssql_python/pybind/connection/connection.cpp
  mssql_python/pybind/ddbc_bindings.cpp
Labels: pr-size: large

#115 FEAT: Linux Test Pipeline
  eng/pipelines/pr-validation-pipeline.yml
  mssql_python/ddbc_bindings.py
Labels: pr-size: medium

#119 FEAT: Build Pipeline & Setup for Linux
  eng/pipelines/build-whl-pipeline.yml
  setup.py
Labels: pr-size: medium

#120 FIX: Ensure graceful cleanup of connection pooling to avoid application hang
  mssql_python/pooling.py
  mssql_python/pybind/connection/connection_pool.cpp
  mssql_python/pybind/connection/connection_pool.h
  mssql_python/pybind/ddbc_bindings.cpp
Labels: pr-size: small

#118 FEAT: Add Default Connection Pooling with User Opt-out Support
  mssql_python/__init__.py
  mssql_python/connection.py
  mssql_python/pooling.py
Labels: pr-size: small

#123 FIX: Ensure cursors are freed before connection (segfault) with added tests
  mssql_python/connection.py
  mssql_python/cursor.py
  tests/test_003_connection.py
  tests/test_004_cursor.py
  tests/test_005_exceptions.py
Labels: pr-size: medium

#124 FEAT: Build Pipeline using docker for Linux multi-distro builds
  eng/pipelines/build-whl-pipeline.yml
  eng/pipelines/pr-validation-pipeline.yml
Labels: pr-size: large

#128 FIX: Robust resource cleanup of Connection/Cursor for graceful exit & add tests
  mssql_python/connection.py
  mssql_python/cursor.py
  tests/test_003_connection.py
  tests/test_005_connection_cursor_lifecycle.py
  tests/test_006_exceptions.py
  tests/test_007_logging.py
Labels: pr-size: medium

#135 FEAT: Adding authentication module and adding new auth types
  README.md
  mssql_python/auth.py
  mssql_python/connection.py
  mssql_python/constants.py
  setup.py
  tests/test_008_auth.py
Labels: pr-size: medium

#132 FEAT: Smoke Testing pip installation on Blank Docker Images
  eng/pipelines/pypi-package-smoketest.yml
Labels: pr-size: small

#137 REFACTOR: Enhance & Fix Logs
  mssql_python/auth.py
  mssql_python/connection.py
  mssql_python/cursor.py
  mssql_python/exceptions.py
  mssql_python/helpers.py
  mssql_python/logging_config.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/unix_utils.cpp
  tests/test_003_connection.py
  tests/test_005_connection_cursor_lifecycle.py
  tests/test_007_logging.py
Labels: pr-size: large

#142 FIX: Interactive on Windows
  mssql_python/auth.py
  tests/test_008_auth.py
Labels: pr-size: small

#144 RELEASE: 0.8.1 (Hotfix)
  setup.py
Labels: pr-size: small
