Repository microsoft/mssql-python, pull requests merged in 2025-09, with the labels that each got.

#208 FEAT: Support correct type handling of None parameters in parameter binding
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
Labels: pr-size: small

#214 FIX: MacOS Pipelines CMake Installation
  eng/pipelines/pr-validation-pipeline.yml
Labels: pr-size: small

#206 FEAT: varcharmax streaming support in execute
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: medium

#224 FIX: Build Pipeline Fix CMake for MacOS
  eng/pipelines/build-whl-pipeline.yml
  eng/pipelines/pr-validation-pipeline.yml
Labels: pr-size: small

#183 FIX: Closed Attribute in cursor `__del__`
  mssql_python/cursor.py
  mssql_python/exceptions.py
  tests/test_003_connection.py
  tests/test_005_connection_cursor_lifecycle.py
Labels: pr-size: medium

#212 FIX: Handle empty data + tests
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: medium

#217 FIX: Executemany String corruption on Unix systems + tests
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: large

#218 FIX: Binary data padding + tests
  mssql_python/cursor.py
  tests/test_004_cursor.py
Labels: pr-size: medium

#221 FEAT: LOB detection and fetch strategy for FetchAll and FetchMany
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: large

#220 FEAT: streaming support in fetchone for nvarcharmax data type
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: large

#230 FEAT: Complex Data Type Support- money & smallmoney
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: medium

#199 FEAT: Adding Columns API in cursor
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  tests/test_004_cursor.py
Labels: pr-size: large

#196 FEAT: Adding primary key API
  mssql_python/constants.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  tests/test_004_cursor.py
Labels: pr-size: large

#195 FEAT: Adding foreignkey API
  mssql_python/constants.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  tests/test_004_cursor.py
Labels: pr-size: large

#193 FEAT: Adding getTypeInfo
  mssql_python/constants.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  tests/test_004_cursor.py
Labels: pr-size: large

#232 FEAT: Streaming support in fetchone, fetchmany, fetchall for varbinarymax data type.
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_004_cursor.py
Labels: pr-size: medium

#215 FIX: Improvement to parameter type inference and handling
  mssql_python/cursor.py
Labels: pr-size: small

#187 FEAT: Adding lowercase for global variable
  mssql_python/__init__.py
  mssql_python/cursor.py
  mssql_python/row.py
  tests/test_001_globals.py
  tests/test_004_cursor.py
Labels: pr-size: large

#188 FEAT: Adding getDecimalSeperator and setDecimalSeperator as global functions
  mssql_python/__init__.py
  mssql_python/cursor.py
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  mssql_python/row.py
  tests/test_001_globals.py
  tests/test_004_cursor.py
Labels: pr-size: large

#189 FEAT: Adding execute in connection class
  mssql_python/connection.py
  mssql_python/cursor.py
  tests/test_001_globals.py
  tests/test_003_connection.py
  tests/test_004_cursor.py
Labels: pr-size: large

#190 FEAT: Adding Ouput Converter APIs
  mssql_python/connection.py
  mssql_python/row.py
  requirements.txt
  tests/test_003_connection.py
  tests/test_004_cursor.py
Labels: pr-size: large

#201 FEAT: Adding getInfo
  mssql_python/connection.py
  mssql_python/constants.py
  mssql_python/pybind/connection/connection.cpp
  mssql_python/pybind/connection/connection.h
  mssql_python/pybind/ddbc_bindings.cpp
  mssql_python/pybind/ddbc_bindings.h
  tests/test_001_globals.py
  tests/test_003_connection.py
  tests/test_004_cursor.py
Labels: pr-size: large

#262 RELEASE: 0.12.0
  PyPI_Description.md
  setup.py
Labels: pr-size: small

#260 FEAT: datetimeoffset support in executemany()
  mssql_python/cursor.py
  mssql_python/msvcp140.dll
  mssql_python/pybind/ddbc_bindings.cpp
  tests/test_003_connection.py
  tests/test_004_cursor.py
Labels: pr-size: medium

#263 FIX: cursor.rowcount
  mssql_python/cursor.py
  tests/test_004_cursor.py
Labels: pr-size: medium
